language: python

python:
  - "3.5"

install:
  pip install codecov pytest-cov pandas openpyxl xlrd xlwt

script:
  py.test --cov=oommfodt --cov-config .coveragerc

after_success:
  codecov

notifications:
  slack: joommf:eqKxGPXuUP3LxnOfxg7GWgDF
